#!/usr/bin/env bash

# Mac Command Line Tools
xcode-select -p &> /dev/null
if [ $? != 0 ]; then
  xcode-select --install
fi

# Homebrew
which brew 1>&/dev/null
if [[ $? != 0 ]] ; then
  curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
  brew update --quiet
fi

# Ansible
brew install ansible --quiet
