- name: git personal email
  git_config:
    name: user.email
    scope: global
    value: "bronek@fastmail.fm"
  tags:
    - git

- name: Git name
  git_config:
    name: user.name
    scope: global
    value: "Bronek Szulc"
  tags:
    - git
