- name: zsh
  homebrew:
    name: zsh
  tags:
    - brew-i
    - zsh

- name: change shell to zsh
  become: true
  user:
    name: "{{ user }}"
    shell: /bin/zsh
  tags:
    - zsh

- name: oh-my-zsh
  become: true
  shell: curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
  when: oh_my_stats.stat.exists == False
  tags:
    - zsh

- name: plugin zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags:
    - zsh
